### ISSUE TITLE
Follow on from proof of concept

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#3]
This is a placeholder for miscellaneous todos collected during rapid prototyping

```[tasklist]
### Tasks
- [x] Create an interface implemented by the primary bridge and its auxiliary contracts
- [ ] Determine bridge-deployed ERC721 & ERC20 symbol conventions
- [ ] Optimize internal interfaces to prevent duplicate calls - e.g. owner checks across bridge & locker contracts, etc.
- [x] Add method for onboarding EVM-native NFTs
- [x] Update getter methods to `view` once the EVM contract supports it for pre- & post- checks - e.g. EVM.BridgedAccount.address() calls
- [x] Add `evmAddressRequiresOnboarding()` method to complement `typeAddressRequiresOnboarding()`
- [x] Update entitlements once EVM contract supports them
- [x] Implement `deployDefiningContract()` to support EVM-native path bridging to Cadence for the first time
- [x] Implement fungible token path for both Flow- & EVM-native tokens
- [x] Implement FungibleToken locker Cadence contract
- [x] Implement defining NonFungibleToken Cadence contract
- [x] Implement defining FungibleToken Cadence contract
- [x] Implement defining ERC20 contract
- [x] Create supporting solidity interfaces
- [x] Add admin resource to template serving contract
- [x] Either validate bytes4 for `supportsInterface` calls or implement the method in the factory contract & expose in Cadence method
- [x] Validate hardcoded gas values for contract calls
- [x] Add EVMAddress to IEVMBridgeNFTLocker events once address() is view
- [x] Update NFT & FT interfaces based on finalized v2 standards
```

**Comment by sisyphusSmiling** [comment]
Closing as this was placeholder for miscellaneous todos throughout code and most all have since been addressed
