### ISSUE TITLE
Integrate existing Previewnet bridge deployment with updated EVM contract

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#40]
### Issue To Be Solved
Once the updated interface is merged to the flow-go `feature/stable-cadence` branch (see https://github.com/onflow/flow-go/pull/5677 and https://github.com/onflow/flow-go/pull/5716 - reflected also in this repo in #39), the EVM contract currently on Previewnet will need to be updated to reflect those changes.

In addition, the `FlowEVMBridgeAccessor` will need to be subsequently deployed and the EVM account will need to claim the resulting `BridgeAccessor` Capability and save it in a `BridgeRouter` at `/storage/evmBridgeRouter` to complete the EVM-Bridge integration (see [`claim_accessor_capability_and_save_router`](https://github.com/onflow/flow-evm-bridge/blob/main/cadence/transactions/bridge/admin/claim_accessor_capability_and_save_router.cdc))

```[tasklist]
### Tasks
- [x] Merge https://github.com/onflow/flow-go/pull/5677
- [x] Approve and merge https://github.com/onflow/flow-go/pull/5716
- [x] Approve and merge #39 to reflect dependency in this repo
- [x] Update `EVM` contract on Previewnet
- [x] Deploy `FlowEVMBridgeAccessor` to bridge account
- [x] Execute `claim_accessor_capability_and_save_router`](https://github.com/onflow/flow-evm-bridge/blob/main/cadence/transactions/bridge/admin/claim_accessor_capability_and_save_router.cdc) from EVM account to complete bridge integration
```
