### ISSUE TITLE
Generate FLIX templates from transactions & scripts

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#41]
### Issue To Be Solved
FLIX is a helpful tool for developers, enabling them to execute scripts & transactions from remote templates without the need to configure a project themselves will all dependencies.

```[tasklist]
### Tasks
- [ ] Add a `cadence/flix` directory to this repo containing FLIX templates of all commonly used scripts and transactions
- [ ] Direct developers to use these templates
- [ ] Add these templates to [onflow/flow-interaction-template-service](https://github.com/onflow/flow-interaction-template-service)
```

**Comment by sisyphusSmiling** [comment]
Since FLIX templates are pinned to their dependencies, this task is blocked by #40
