### ISSUE TITLE
Update COA bridging interfaces

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#45]
### Issue To Be Solved
There are currently four bridge-related methods on the COA
- `depositNFT` - bridge NFT to EVM
- `withdrawNFT` - bridge NFT from EVM
- `depositTokens` - bridge FT to EVM
- `withdrawTokens` - bridge FT from EVM

It's been suggested that at least some of these methods be renamed to include the target ERC. Changes to these will have downstream effects on integrated applications, including developer tooling so it will be important to make these updates before more widespread integration.

```[tasklist]
### Tasks
- [ ] Decide on naming conventions. If changes deemed, continue
- [ ] Update EVM contract and bridging transactions in this repo
- [ ] Update EVM contract in flow-go
- [ ] Update EVM contract on PreviewNet
```
