### ISSUE TITLE
Redeploy contracts to Previewnet

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#59]
### Issue To Be Solved
Breaking changes over recent iterations require a redeployment of bridge contracts. Documentation and configs should be updated once the deployment is complete

```[tasklist]
### Tasks
- [ ] Update MetadataViews on Previewnet with content from https://github.com/onflow/flow-nft/commit/40c3de711140ab3f4b04fad07fb19eb32de63065
- [ ] Deploy to a new Previewnet account
- [ ] Update deployment address & flow.json
```
