### ISSUE TITLE
Prepare FlowEVMBridgeHandlerInterfaces for dependency migration

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-evm-bridge#64]
### Issue To Be Solved
In order for handled tokens to integrate with the bridge, they will need to implement `FlowEVMBridgeHandlerInterfaces.TokenMinter` in their minter resources. It will be easiest for them to do this before network migration, and in order to do so, a Cadence 0.42 version of the contract will need be deployed to Testnet. This contract will also need to be staged so the contract and its dependencies can be migrated.

```[tasklist]
### Tasks
- [x] Create a feature branch containing a version of `FlowEVMBridgeHandlerInterfaces` that is compatible with Testnet Cadence and current deployments of the EVM contract - likely just containing the `TokenMinter` resource interface
- [x] Deploy this contract to Testnet
- [x] Stage the 1.0 version on Testnet
```
